$('header').addClass('masthead');
$('h1').removeClass('big-heading');
$('main').addClass('wrapper');
$('p:first-child').addClass('intro');
$('h2').addClass('slug-head');
$('ul').addClass('slug-list');
$('img').addClass('slug-img');
$('ul li:first-child').addClass('slug-list-first');
$('ul li:last-child').addClass('slug-list-last');
$('dl').addClass('classification');
$('dt').removeClass('big-label');
$('ul li:last-child').show();
